### PR TITLE
implement expanded version comparison

### PR DESCRIPTION
**Pull request by moehreag**
Would like to get your opinion on these changes first..

### CODE REVIEW

**Review by TheKodeToad — CHANGES_REQUESTED** [review]
This is hard to read, but I don't know how much that could be improved considering the complexity and inconsistency of minecraft versions. I think you forgot to parse release candidates though!

**Comment by moehreag** [comment]
> This is hard to read, but I don't know how much that could be improved considering the complexity and inconsistency of minecraft versions. I think you forgot to parse release candidates though!

I did indeed.

**Comment by TheKodeToad** [comment]
Hmm, I think it's possible not to duplicate the prerelease parsing?

**Comment by TheKodeToad** [comment]
Oh, and also I'm pretty sure this will break for snapshots
https://github.com/AxolotlClient/AxolotlClient-installer/blob/cf2f821a2b6259bcb5de768d11aca305cc20734e/src/main/java/io/github/axolotlclient/installer/Installer.java#L126

**Review by TheKodeToad — APPROVED** [review]

**Pull request merged**
